### ISSUE TITLE
Roadmap for version 1.0

### ISSUE THREAD

**Issue by RomainLanz** [Slynova-Org/flydrive#87]
We are planning to release Flydrive version 1.0 soon. This will be a relatively huge release that include a number of necessary breaking changes.

The code of the release is currently in the [`next`](https://github.com/Slynova-Org/flydrive/tree/next) branch.

## Planned Feature

* [x] Manager [TypeScript Rewrite] (https://github.com/Slynova-Org/flydrive/commit/c71721c308bff3f8f3d62ea64b46493218731980)
* [x] LocalFileStorage [TypeScript Rewrite] (https://github.com/Slynova-Org/flydrive/commit/cc7bce9f9ceaaa7bb6d77d48285885480c854d9e)
* [x] Google Cloud Storage Driver (https://github.com/Slynova-Org/flydrive/pull/81) 
* [x] AWSS3 [TypeScript Rewrite] (https://github.com/Slynova-Org/flydrive/commit/5f9021775b4489bba6dd2c25735457ef8be04121)
* [x] Docker Testing for S3/Spaces/Minio and more (https://github.com/Slynova-Org/flydrive/pull/54, https://github.com/Slynova-Org/flydrive/commit/5a6c34d7e561ac1250cb87e07bacee5d704e2e7b, https://github.com/Slynova-Org/flydrive/commit/6f83ecc7e55f91ac560d2b2a2e1a305d8f4406b1)
* [x] Ensure consistency across all drivers (https://github.com/Slynova-Org/flydrive/pull/104)
* [ ] Improvement of the documentation
  * [ ] Docblocks
  * [ ] Method examples
  * [ ] Running tests
  * [ ] Extending the manager

## Nice to have (could wait until after 1.0)

* [x] `list(location: string)`
* [ ] `copyToDisk(location: string, dest: string, destDisk: Storage)`
* [ ] `moveToDisk(location: string, dest: string, destDisk: Storage)`
* [x] `getTimestamp(location: string)`

#### No more FTP!

The FTP driver has been removed and will probably not be added again. Feel free to create you own driver and extend the manager with it.

#### No more proxies!

Proxies have been removed, that means we doesn't support magic method forwarding anymore. You will need to build an abstraction around it (like it's done in the Adonis implementation) if you want to keep this feature.

```javascript
// Before
storage.exists(...)

// Now
storage.disk().exists(...)
```

```javascript
storage.disk() // Returns the default disk (specified in the config)
storage.disk('awsCloud') // Returns the driver for the disk "awsCloud"
storage.disk('awsCloud', customConfig) // Overwrite the default configuration of the disk
```

#### Consistent returns/exceptions!

Since all drivers will have a consistent returns you will need to adapt your code to the new interface/abstraction we will create.

A good example is the `put` method that currently only return a `boolean` to give you insight if the file as been written or not.

However, some drivers like `S3` return many information about the new file (https://github.com/Slynova-Org/flydrive/issues/52). To avoid loosing those information we will create a common response object for those methods that will have always the same properties across all drivers.

If we don't handle a specific use case you will still be able to access the real response by using the `raw` property.

**Comment by RomainLanz** [comment]
Premajor 1.0.0-0 has been released!
You can try it with the `@next` tag on NPM.

**Comment by oanhnn** [comment]
Does the project have any new update?

**Comment by RomainLanz** [comment]
We are very close to release!
You can already use the 1.0 version with the `@next` tag on `npm`.

**Comment by jrbarnard** [comment]
Hi @RomainLanz, is there an update on the eta for version 1?
Cheers!

**Comment by RomainLanz** [comment]
Hey @jrbarnard! 👋 

Planned for this week!

**Comment by annymosse** [comment]
@RomainLanz is this version affect adonis v4 or not ?

**Comment by rizalashidiq97** [comment]
Is there any update ? I want to extend the manager for google drive

**Comment by annymosse** [comment]
@rizalashidiq97 there's no need to do that, this version contain google cloud storage already see PR #81
